@startuml

hide class circle
skinparam ClassBorderColor black
skinparam ArrowColor black
skinparam BorderColor black 
skinparam linetype ortho

class "dcat:Catalog" <<mandatory>> {
    <<mandatory>>   dct:title    ~> rdfs:Literal [1..*]
    <<recommended>> dct:modified ~> rdfs:Literal [0..1]
    <<optional>>    dcat:catalog ~> dcat:Catalog [0..1]
}
    '@ rdfs:label      = Katalog
    '@ _:internalLink  = #klasse-katalog
    '@ rdf:about       = http://www.w3.org/ns/dcat#Catalog

"dcat:Catalog" --> "*" "dcat:Catalog" : <<optional>> dct:hasPart
    '@ rdfs:label      = Hat Teilkatalog
    '@ _:internalLink  = katalog-hat-teilkatalog

@enduml